﻿services:
  template_asp.net_application:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    container_name: template_asp.net_application
    image: template_asp.net_application
    build:
      context: .
      dockerfile: template_asp.net_application/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      database.server:
        condition: service_healthy
  
  database.server:
    image: "mcr.microsoft.com/mssql/server"
    container_name: database.server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=sa
      - SA_PASSWORD=1
    volumes:
      - ./sqlserver/data:/var/opt/mssql/data
      - ./sqlserver/log:/var/opt/mssql/log
        
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "1" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s